// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvu0qD04nkrbjLNChJwSahJdSZKh9-VYM',
    appId: '1:856962758049:web:f382a8081e1a7d982c47e0',
    messagingSenderId: '856962758049',
    projectId: 'vipnni-bb870',
    authDomain: 'vipnni-bb870.firebaseapp.com',
    databaseURL: 'https://vipnni-bb870-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vipnni-bb870.appspot.com',
    measurementId: 'G-XMN3NHYQK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXGp7QGtPyiD-autMIF-ltAo6KrhXA6Y',
    appId: '1:856962758049:android:9daf26bdaebed3052c47e0',
    messagingSenderId: '856962758049',
    projectId: 'vipnni-bb870',
    databaseURL: 'https://vipnni-bb870-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vipnni-bb870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9NZdGK7BOk7lDNZKiMCtwGfknoc8HB6g',
    appId: '1:856962758049:ios:f3bf7d3a6d6d6c522c47e0',
    messagingSenderId: '856962758049',
    projectId: 'vipnni-bb870',
    databaseURL: 'https://vipnni-bb870-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vipnni-bb870.appspot.com',
    androidClientId: '856962758049-djgrtqksrtc2bf58c8h1m3viitfvbmh1.apps.googleusercontent.com',
    iosClientId: '856962758049-jlj20e81rf1jo3duhrjqhk7d8oanbspf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vipnni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9NZdGK7BOk7lDNZKiMCtwGfknoc8HB6g',
    appId: '1:856962758049:ios:f3bf7d3a6d6d6c522c47e0',
    messagingSenderId: '856962758049',
    projectId: 'vipnni-bb870',
    databaseURL: 'https://vipnni-bb870-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vipnni-bb870.appspot.com',
    androidClientId: '856962758049-djgrtqksrtc2bf58c8h1m3viitfvbmh1.apps.googleusercontent.com',
    iosClientId: '856962758049-jlj20e81rf1jo3duhrjqhk7d8oanbspf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vipnni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvu0qD04nkrbjLNChJwSahJdSZKh9-VYM',
    appId: '1:856962758049:web:cc4fdea26c2bbf162c47e0',
    messagingSenderId: '856962758049',
    projectId: 'vipnni-bb870',
    authDomain: 'vipnni-bb870.firebaseapp.com',
    databaseURL: 'https://vipnni-bb870-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vipnni-bb870.appspot.com',
    measurementId: 'G-M3KDCSPJQ0',
  );

}